// auto generated by go tool dist

package runtime

const defaultGoroot = `/home/lsub/sys/golang`
const theVersion = `devel +95c8c27 Sun Jun 14 11:54:10 2015 +0200`
const goexperiment = ``
const stackGuardMultiplier = 1
var buildVersion = theVersion
